### ISSUE TITLE
Sherlock workflow fails when no JS code block is present

### ISSUE THREAD

**Issue by sargunv** [arcanis/sherlock#8]
I just opened an issue over at https://github.com/yarnpkg/berry/issues/2517 and got a bunch of emails telling me "Run failed: Sherlock for Yarn". Looking at the actual run, the error appears to be because "no JS code block got found". https://github.com/yarnpkg/berry/runs/1976830896?check_suite_focus=true#step:5:172. I assume this workflow should simply be a no-op when no JS test case is present in the issue instead of failing a bunch?

![image](https://user-images.githubusercontent.com/1320357/109116147-ec179b80-76f4-11eb-97c8-190c4d7825b0.png)

**Comment by arcanis** [comment]
The reason for that is that we need to "cancel" the subsequent job steps when there's no code, but GitHub doesn't support [neutral exit code](https://github.com/actions/toolkit/issues/146) or similar feature (to the best of my knowledge?).

**Comment by sargunv** [comment]
Oh, I usually do that by setting an output on the step that determines whether to continue, and then something like `if: ${{ steps.blah.outputs.should-continue }}` on all subsequent steps.

**Comment by arcanis** [comment]
That seems a good idea - is that something you could PR in [our workflow](https://github.com/yarnpkg/berry/blob/master/.github/workflows/sherlock-workflow.yml)? This part of the integration isn't stored in this repository 🤔

**Comment by sargunv** [comment]
Sure, I'll try to do that this weekend, both in the readme here and in the
real workflow in the Berry repo.

Some implementation questions before I start on that:

The easy solution here is to just skip subsequent steps when the "payload"
step fails, but that might hide other, unexpected, types of failure that we
probably don't want to hide (?).

A better approach would be to check the output and only skip subsequent
steps if the specific failure type was this "no JS code block found" case.
Does the sherlock script output a specific exit code for that, or would I
have to parse the text output?

Or, maybe just go ahead and add that exit code if it doesn't already have
it?
